print("Please enter a character for the eye")
eye = input()

print(" ##########")
print("##   "+eye+" "+eye+"  ##")
print("##  ----  ##")
print(" ##########")
print(" ##########")
print("  ######## ")
print("  #------# ")
print(" #O**######")
print(" ##########")
print("  ######## ")
print("   ######  ")
print("   ######   ")